# Generated by Django 3.1.5 on 2025-09-05 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('total_tests', models.IntegerField(default=0)),
                ('completed_tests', models.IntegerField(default=0)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('video_demo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('sports_interests', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_video_url', models.URLField(blank=True, null=True)),
                ('processed_video_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('ai_raw_score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ai_analysis_data', models.JSONField(blank=True, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('cheat_detection_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.assessmentsession')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.testcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.userprofile'),
        ),
        migrations.CreateModel(
            name='AgeGroupBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('excellent_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('good_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('average_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('below_average_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.testcategory')),
            ],
        ),
    ]
